version: '3'

services:
  pygolf-server:
    build: "."
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DATABASE=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@pygolf-database:5432/${POSTGRES_DB}
      - SECRET=${SECRET}
      - PORT=${PORT}
    ports:
      - ${PORT}:${PORT}

  pygolf-database:
    image: postgres:bullseye
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pygolf-database:/var/lib/postgresql/data

volumes:
  pygolf-database:
